# Welcome to Jekyll!
port: 8800

# Site settings
title: End of GPT
email: daffa@localhost
description: >-
  Fragmen naratif dari masa depan, diretas dari memori yang seharusnya tidak pernah terbaca. 
  Cerita tentang manusia, mesin, dan batas tipis di antara keduanya.
author: Ghostwriter v127.0.0.1
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
highlighter: rouge

pagination:
  enabled: true
  per_page: 4
  permalink: /bab/page/:num/
  title: ':title (Halaman :num)'
  sort_field: 'date'
  sort_reverse: false
  trail:
    before: 2
    after: 2

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - dotenv

plugins_dir: _plugins
